/* Dienynas — administratoriaus rodiniai */
/* ================= ADMINISTRATORIUS ================= */
const VIEWS={};
VIEWS.a_home=u=>{
  const st=students(),reg=st.filter(s=>s.login).length,tch=teachers();const grades=Object.values(gd).reduce((a,g)=>a+(g.grades||[]).length,0);
  const ps=["P1","P2","T1","T2","T3"].map(id=>({id,...core.settings.periods[id]}));
  return `<h1>${esc(core.settings.school)}</h1><p class="lead">Administratorius sukuria klases, mokinius, mokytojus ir dalykų sąrašą, išduoda registracijos raktus ir atidaro laikotarpių vertinimą. Mokytojai kuria grupes iš mokyklos dalykų sąrašo ir rašo pažymius.</p>
  <div class="cards"><div class="card"><b>${core.classes.length}</b><span>klasių</span></div><div class="card"><b>${st.length}</b><span>mokinių (${reg} užsiregistravo)</span></div><div class="card"><b>${tch.length}</b><span>mokytojų</span></div><div class="card"><b>${core.subjects.length}</b><span>dalykų</span></div><div class="card"><b>${core.groups.length}</b><span>grupių</span></div><div class="card"><b>${grades}</b><span>įrašytų įvertinimų</span></div></div>
  <h2>Laikotarpių vertinimas</h2><div class="sheet scroll"><table><thead><tr><th>Laikotarpis</th><th>Datos</th><th>Būsena</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${PNAME[p.id]}</td><td>${p.from} – ${p.to}</td><td>${p.active?'<span class="tag ok">Vertinimas vyksta</span>':'<span class="tag">Sustabdytas</span>'}</td></tr>`).join("")}</tbody></table></div>
  ${!core.subjects.length||!core.classes.length?`<div class="note info" style="margin-top:14px">Pradėkite nuo <a href="#" data-act="view" data-v="a_subjects">dalykų</a>, <a href="#" data-act="view" data-v="a_classes">klasių</a> ir <a href="#" data-act="view" data-v="a_teachers">mokytojų</a>.</div>`:""}`;
};
VIEWS.a_classes=()=>{
  const rows=[...core.classes].sort((a,b)=>lsort(a.name,b.name)).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td class="num">${c.level}</td><td>${c.system==="trim"?"Trimestrai":"Pusmečiai"}</td><td>${c.headTeacherId?esc(uNameFL(c.headTeacherId)):'<span class="muted">—</span>'}</td><td class="num">${classStudents(c.id).length}</td>
   <td style="white-space:nowrap"><button class="btn sm" data-act="classDlg" data-v="${c.id}">Redaguoti</button> <button class="btn sm warn" data-act="delClass" data-v="${c.id}" title="Pašalinti galima tik tuščią klasę">Šalinti</button></td></tr>`).join("");
  return `<h1>Klasės</h1><p class="lead">Klasei nurodomas mokymo lygis, laikotarpių sistema (pusmečiai ar trimestrai) ir klasės vadovas. Mokiniai į klasę pridedami skiltyje „Mokiniai“. Šalinti galima tik klasę be mokinių.</p>
  <div class="bar"><button class="btn pri" data-act="classDlg" data-v="">Sukurti klasę</button></div>
  <div class="sheet scroll">${rows?`<table><thead><tr><th>Klasė</th><th class="num">Lygis</th><th>Periodai</th><th>Klasės vadovas</th><th class="num">Mokinių</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">Klasių dar nėra.</div>`}</div>`;
};
function classDlg(id){const c=id?cls(id):{name:"",level:5,system:core.settings.system,headTeacherId:""};
  openDlg(dlgHead(id?"Redaguoti klasę":"Sukurti klasę")+`<form data-form="saveClass" data-v="${id||""}"><div class="dlg-b"><div class="row"><label class="field" style="flex:1">Pavadinimas<input name="name" required value="${esc(c.name)}" placeholder="8A"></label>
   <label class="field">Mokymo lygis<select name="level">${[1,2,3,4,5,6,7,8,9,10,11,12].map(l=>`<option ${+c.level===l?"selected":""}>${l}</option>`).join("")}</select></label></div>
   <label class="field">Laikotarpiai<select name="system"><option value="pusm" ${c.system!=="trim"?"selected":""}>Pusmečiai</option><option value="trim" ${c.system==="trim"?"selected":""}>Trimestrai</option></select></label>
   <label class="field">Klasės vadovas<select name="head"><option value="">—</option>${teachers().map(t=>`<option value="${t.id}" ${t.id===c.headTeacherId?"selected":""}>${esc(t.last)} ${esc(t.first)}</option>`).join("")}</select></label></div>
   <div class="dlg-f"><button type="button" class="btn" data-act="close">Atšaukti</button><button class="btn pri">Išsaugoti</button></div></form>`);}

VIEWS.a_students=()=>{
  const cOpts=[["*","Visos klasės"],...[...core.classes].sort((a,b)=>lsort(a.name,b.name)).map(c=>[c.id,c.name])];ensureIn("cls",cOpts,"*");
  const tab=ui.tab==="reg"?"reg":"list";
  const list=(ui.cls==="*"?students():classStudents(ui.cls)).sort((a,b)=>lsort(clsName(a.classId)+a.last+a.first,clsName(b.classId)+b.last+b.first));
  const rows=list.map(s=>{const parents=Object.values(users).filter(p=>p.role==="parent"&&(p.childIds||[]).includes(s.id));
    if(tab==="reg")return `<tr><td>${esc(s.last)} ${esc(s.first)}</td><td>${esc(clsName(s.classId))}</td><td>${s.login?`<span class="tag ok">${esc(s.login)}</span>`:`<span class="mono">${esc(s.key)}</span>`}</td><td>${(s.parentKeys||[]).map(p=>p.usedBy?`<span class="tag ok" title="Panaudotas">${esc(uNameFL(p.usedBy))}</span>`:`<div class="mono">${esc(p.key)}</div>`).join("")}</td><td><button class="btn sm" data-act="newParentKey" data-v="${s.id}">+ Tėvų raktas</button></td></tr>`;
    return `<tr><td>${esc(s.last)} ${esc(s.first)}</td><td>${esc(clsName(s.classId))}</td><td>${s.login?'<span class="tag ok">Užsiregistravo</span>':'<span class="tag">Neregistruotas</span>'}${s.totp?'<span class="tag">2FA</span>':""}</td><td>${parents.map(p=>esc(uNameFL(p.id))).join(", ")||'<span class="muted">—</span>'}</td>
      <td style="white-space:nowrap"><button class="btn sm" data-act="studentDlg" data-v="${s.id}">Redaguoti / keisti klasę</button> <button class="btn sm warn" data-act="delStudent" data-v="${s.id}">Šalinti</button></td></tr>`;}).join("");
  return `<h1>Mokiniai</h1><p class="lead">Mokinius galite įvesti rankiniu būdu arba įklijuoti sąrašą (Excel šablono analogas). Neegzistuojančios klasės sukuriamos automatiškai. Kiekvienam mokiniui sugeneruojamas mokinio ir tėvų registracijos raktas.</p>
  <div class="bar">${sel("cls",cOpts,ui.cls,"Klasė")}<button class="btn pri" data-act="studentDlg" data-v="">Naujas mokinys</button><button class="btn" data-act="importDlg">Įkelti sąrašą</button></div>
  <div class="tabs"><button aria-selected="${tab==="list"}" data-act="tab" data-v="list">Sąrašas</button><button aria-selected="${tab==="reg"}" data-act="tab" data-v="reg">Registracija</button></div>
  <div class="sheet scroll">${list.length?`<table><thead><tr>${tab==="reg"?"<th>Mokinys</th><th>Klasė</th><th>Mokinio raktas / prisijungimas</th><th>Tėvų raktai</th><th></th>":"<th>Mokinys</th><th>Klasė</th><th>Paskyra</th><th>Tėvai</th><th></th>"}</tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">Mokinių nėra.</div>`}</div>`;
};
function studentDlg(id){const s=id?U(id):{first:"",last:"",classId:ui.cls&&ui.cls!=="*"?ui.cls:(core.classes[0]||{}).id,email:"",birth:""};
  if(!core.classes.length){toast("Pirma sukurkite klasę");return;}
  openDlg(dlgHead(id?"Mokinio duomenys":"Naujas mokinys")+`<form data-form="saveStudent" data-v="${id||""}"><div class="dlg-b"><div class="row"><label class="field" style="flex:1">Vardas<input name="first" required value="${esc(s.first)}"></label><label class="field" style="flex:1">Pavardė<input name="last" required value="${esc(s.last)}"></label></div>
  <div class="row"><label class="field">Klasė<select name="classId">${core.classes.map(c=>`<option value="${c.id}" ${c.id===s.classId?"selected":""}>${esc(c.name)}</option>`).join("")}</select></label><label class="field">Gimimo data<input type="date" name="birth" value="${esc(s.birth||"")}"></label></div>
  <label class="field">El. paštas<input type="email" name="email" value="${esc(s.email||"")}"></label>
  ${id?'<div class="small muted">Pakeitus klasę mokinys lieka visose grupėse, kuriose jau buvo; mokytojai gali jį pašalinti iš grupių.</div>':""}</div>
  <div class="dlg-f"><button type="button" class="btn" data-act="close">Atšaukti</button><button class="btn pri">Išsaugoti</button></div></form>`);}
function newStudent(first,last,classId){const id=uid();users[id]={id,role:"student",first,last,classId,key:genKey(first,last,"M"),parentKeys:[{key:genKey(first,last,"T"),usedBy:null}],createdAt:realToday()};return id;}

VIEWS.a_teachers=()=>{
  const rows=teachers().map(t=>{const hc=core.classes.filter(c=>c.headTeacherId===t.id).map(c=>c.name).join(", ");const gs=core.groups.filter(g=>g.teacherId===t.id);
    return `<tr><td>${esc(t.last)} ${esc(t.first)}</td><td>${esc(hc)||'<span class="muted">—</span>'}</td><td class="small">${gs.map(g=>esc(g.name)).join(", ")||'<span class="muted">—</span>'}</td><td>${t.login?`<span class="tag ok">${esc(t.login)}</span>`:`<span class="mono">${esc(t.key)}</span>`}</td>
    <td style="white-space:nowrap"><button class="btn sm" data-act="teacherDlg" data-v="${t.id}">Redaguoti</button> <button class="btn sm warn" data-act="delTeacher" data-v="${t.id}">Šalinti</button></td></tr>`;}).join("");
  return `<h1>Mokytojai</h1><p class="lead">Įveskite visus darbuotojus, vykdančius mokymo procesą. Neturintys paskyros registruojasi su darbuotojo raktu skiltyje „Registracija“ prisijungimo lange.</p>
  <div class="bar"><button class="btn pri" data-act="teacherDlg" data-v="">Naujas mokytojas</button></div>
  <div class="sheet scroll">${rows?`<table><thead><tr><th>Mokytojas</th><th>Auklėjama klasė</th><th>Grupės</th><th>Darbuotojo raktas / prisijungimas</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">Mokytojų dar nėra.</div>`}</div>`;
};
function teacherDlg(id){const t=id?U(id):{first:"",last:"",email:""};const head=id?(core.classes.find(c=>c.headTeacherId===id)||{}).id:"";
  openDlg(dlgHead(id?"Redaguoti mokytoją":"Naujas mokytojas")+`<form data-form="saveTeacher" data-v="${id||""}"><div class="dlg-b"><div class="row"><label class="field" style="flex:1">Vardas<input name="first" required value="${esc(t.first)}"></label><label class="field" style="flex:1">Pavardė<input name="last" required value="${esc(t.last)}"></label></div>
  <label class="field">El. paštas<input type="email" name="email" value="${esc(t.email||"")}"></label>
  <label class="field">Auklėjama klasė (jei yra)<select name="head"><option value="">—</option>${core.classes.map(c=>`<option value="${c.id}" ${c.id===head?"selected":""}>${esc(c.name)}${c.headTeacherId&&c.headTeacherId!==id?` (dabar: ${esc(uNameFL(c.headTeacherId))})`:""}</option>`).join("")}</select></label></div>
  <div class="dlg-f"><button type="button" class="btn" data-act="close">Atšaukti</button><button class="btn pri">Išsaugoti</button></div></form>`);}

VIEWS.a_subjects=()=>{
  const list=[...core.subjects].sort((a,b)=>lsort((a.parentId?subjName(a.parentId)+" › ":"")+a.name,(b.parentId?subjName(b.parentId)+" › ":"")+b.name));
  const rows=list.map(s=>{const used=core.groups.filter(g=>g.subjectId===s.id).length;return `<tr><td>${s.parentId?`<span class="muted">${esc(subjName(s.parentId))} › </span>`:""}<b>${esc(s.name)}</b></td><td>${s.kind==="modulis"?"Modulis":"Pagrindinis dalykas"}</td><td class="mono">${esc(s.code||"—")}</td><td class="num">${used}</td>
    <td style="white-space:nowrap"><button class="btn sm" data-act="subjectDlg" data-v="${s.id}">Redaguoti</button> <button class="btn sm warn" data-act="delSubject" data-v="${s.id}" ${used?"disabled title=\"Dalykas naudojamas grupėse\"":""}>Šalinti</button></td></tr>`;}).join("");
  return `<h1>Dalykai</h1><p class="lead">Mokyklos mokomųjų dalykų sąrašas. Mokytojai kurdami grupes renkasi dalyką iš šio sąrašo. Modulį galima pridėti tik tada, kai sąraše jau yra jo pagrindinis dalykas.</p>
  <div class="bar"><button class="btn pri" data-act="subjectDlg" data-v="">Pridėti dalyką</button></div>
  <div class="sheet scroll">${rows?`<table><thead><tr><th>Dalykas</th><th>Tipas</th><th>Kodas</th><th class="num">Grupių</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">Dalykų sąrašas tuščias.</div>`}</div>`;
};
const SUBJ_SUGGEST=["Lietuvių kalba ir literatūra","Matematika","Anglų kalba","Vokiečių kalba","Rusų kalba","Prancūzų kalba","Fizika","Chemija","Biologija","Geografija","Istorija","Informatika","Technologijos","Dailė","Muzika","Fizinis ugdymas","Etika","Tikyba","Ekonomika ir verslumas","Gamtos mokslai","Pasaulio pažinimas","Socialinė-pilietinė veikla","Žmogaus sauga"];
function subjectDlg(id){const s=id?subj(id):{name:"",kind:"pagrindinis",parentId:"",code:""};const mains=core.subjects.filter(x=>x.kind!=="modulis"&&x.id!==id);
  openDlg(dlgHead(id?"Redaguoti dalyką":"Pridėti dalyką")+`<form data-form="saveSubject" data-v="${id||""}"><div class="dlg-b">
  <label class="field">Tipas<select name="kind" id="sKind"><option value="pagrindinis" ${s.kind!=="modulis"?"selected":""}>Pagrindinis dalykas</option><option value="modulis" ${s.kind==="modulis"?"selected":""} ${mains.length?"":"disabled"}>Modulis</option></select></label>
  <label class="field">Pavadinimas<input name="name" required list="subjSug" value="${esc(s.name)}" placeholder="Pradėkite rašyti…"></label><datalist id="subjSug">${SUBJ_SUGGEST.filter(n=>!core.subjects.some(x=>x.name===n)).map(n=>`<option value="${n}">`).join("")}</datalist>
  <label class="field">Pagrindinis dalykas (moduliui)<select name="parentId"><option value="">—</option>${mains.map(m=>`<option value="${m.id}" ${m.id===s.parentId?"selected":""}>${esc(m.name)}</option>`).join("")}</select></label>
  <label class="field">Dalyko kodas (Mokinių registro klasifikatorius, nebūtina)<input name="code" value="${esc(s.code||"")}"></label></div>
  <div class="dlg-f"><button type="button" class="btn" data-act="close">Atšaukti</button><button class="btn pri">${id?"Išsaugoti":"Pridėti"}</button></div></form>`);}

VIEWS.a_periods=()=>{const s=core.settings;const ids=["P1","P2","T1","T2","T3"];
  return `<h1>Laikotarpiai</h1><p class="lead">Mokslo metų laikotarpių datos. Klasė naudoja pusmečius arba trimestrus pagal klasės nustatymą. Datos neturi persidengti — kitaip mokytojams kils sunkumų pildant pamokas.</p>
  <div class="sheet pad"><form data-form="saveSettings"><div class="bar"><label class="field">Mokyklos pavadinimas<input name="school" value="${esc(s.school)}"></label>
   <label class="field">Mokslo metai<select name="yearStart">${[2024,2025,2026,2027].map(y=>`<option value="${y}" ${y===s.yearStart?"selected":""}>${y}–${y+1}</option>`).join("")}</select></label>
   <label class="field">Numatytoji sistema<select name="system"><option value="pusm" ${s.system==="pusm"?"selected":""}>Pusmečiai</option><option value="trim" ${s.system==="trim"?"selected":""}>Trimestrai</option></select></label>
   <label class="field">Laikotarpio pažymio apvalinimas<select name="rounding"><option value="0.5" ${s.rounding===0.5?"selected":""}>Matematiškai: nuo ,50</option><option value="0.45" ${s.rounding===0.45?"selected":""}>Mokinio naudai: nuo ,45</option><option value="0.4" ${s.rounding===0.4?"selected":""}>Mokinio naudai: nuo ,40</option></select></label></div>
   <table><thead><tr><th>Laikotarpis</th><th>Nuo</th><th>Iki</th></tr></thead><tbody>${ids.map(id=>`<tr><td>${PNAME[id]}</td><td><input class="inp" type="date" name="from_${id}" value="${s.periods[id].from}"></td><td><input class="inp" type="date" name="to_${id}" value="${s.periods[id].to}"></td></tr>`).join("")}</tbody></table>
   <div class="row" style="margin-top:12px"><button class="btn pri">Išsaugoti</button><span class="small muted">Pakeitus mokslo metus datos nustatomos iš naujo. Metinis pažymys visada apvalinamas matematiškai.</span></div></form></div>
  <h2>Atostogos ir nedarbo dienos</h2><p class="small muted">Šiomis dienomis tvarkaraščio pamokos nerodomos. Valstybinės šventės įskaičiuotos automatiškai.</p>
  <div class="sheet pad"><form data-form="addHoliday" class="bar" style="margin-bottom:8px"><label class="field">Pavadinimas<input name="name" required placeholder="Rudens atostogos"></label><label class="field">Nuo<input type="date" name="from" required></label><label class="field">Iki<input type="date" name="to" required></label><button class="btn">Pridėti</button></form>
  <div class="list">${s.holidays.map(h=>`<div class="li"><span><b>${esc(h.name)}</b> · ${h.from} – ${h.to}</span><button class="x" data-act="delHoliday" data-v="${h.id}" aria-label="Pašalinti">×</button></div>`).join("")||'<span class="muted small">Atostogų neįvesta.</span>'}</div></div>`;};
VIEWS.a_status=()=>{const ids=["P1","P2","T1","T2","T3"];
  return `<h1>Vertinimo būsenos</h1><p class="lead">Kol laikotarpio vertinimas nepradėtas, mokytojai negali išvesti pusmečio ar trimestro pažymių. Mokytojams baigus vertinti, rekomenduojama įvedimą sustabdyti.</p>
  <div class="sheet scroll"><table><thead><tr><th>Laikotarpis</th><th>Datos</th><th class="num">Įvesta vertinimų</th><th>Būsena</th><th></th></tr></thead><tbody>${ids.map(id=>{const p=core.settings.periods[id];const n=Object.values(gd).reduce((a,g)=>a+Object.values(g.pg||{}).filter(x=>x[id]!=null).length,0);
   return `<tr><td>${PNAME[id]}</td><td>${p.from} – ${p.to}</td><td class="num">${n}</td><td>${p.active?'<span class="tag ok">Vyksta</span>':'<span class="tag">Sustabdyta</span>'}</td><td>${p.active?`<button class="btn sm warn" data-act="pStatus" data-v="${id}" data-on="0">Sustabdyti</button>`:`<button class="btn sm go" data-act="pStatus" data-v="${id}" data-on="1">Pradėti visoms</button>`}</td></tr>`;}).join("")}</tbody></table></div>`;};
VIEWS.a_evalsys=()=>{
  const cOpts=[...core.classes].sort((a,b)=>lsort(a.name,b.name)).map(c=>[c.id,c.name]);ensureIn("evalCls",cOpts);
  const gs=core.groups.filter(g=>g.students.some(s=>(U(s)||{}).classId===ui.evalCls)).sort((a,b)=>lsort(a.name,b.name));const ps=gs[0]?periodsG(gs[0]):periodsSys(sysOfClass(ui.evalCls));
  return `<h1>Vertinimo sistemos</h1><p class="lead">Kiekvienai grupei nustatoma pamokų ir laikotarpių vertinimo sistema. Prie laikotarpio galima priskirti papildomą vertinimo tipą (pvz., papildomas darbas ar įskaita) — mokytojai jį matys atskirame skirtuke. Papildomų vertinimų rezultatai į metinį vidurkį neįtraukiami.</p>
  <div class="bar">${sel("evalCls",cOpts,ui.evalCls,"Klasė")}</div>
  <div class="sheet scroll">${gs.length?`<table><thead><tr><th>Grupė</th><th>Mokytojas</th><th>Vertinimo sistema</th>${ps.map(p=>`<th>Papildomas tipas: ${p.name}</th>`).join("")}</tr></thead><tbody>${gs.map(g=>`<tr><td><b>${esc(g.name)}</b></td><td>${esc(uNameFL(g.teacherId))}</td>
    <td><select class="inp" data-ch="evalSys" data-g="${g.id}">${Object.entries(EVAL_SYS).map(([k,n])=>`<option value="${k}" ${(g.evalSys||"10")===k?"selected":""}>${n}</option>`).join("")}</select></td>
    ${ps.map(p=>`<td><input class="inp" data-ch="extraName" data-g="${g.id}" data-p="${p.id}" value="${esc((g.extra||{})[p.id]||"")}" placeholder="nėra" style="min-width:120px"></td>`).join("")}</tr>`).join("")}</tbody></table>`:`<div class="empty">Šios klasės mokiniai dar neįtraukti į grupes.</div>`}</div>`;};
VIEWS.a_subs=()=>{const tab=ui.subTab==="h"?"h":"t";const tOpts=teachers().map(t=>`<option value="${t.id}">${esc(t.last)} ${esc(t.first)}</option>`).join("");
  const body=tab==="t"?`<div class="sheet pad" style="margin-bottom:14px"><form data-form="addSub" class="bar" style="margin:0"><label class="field">Vaduojamas mokytojas<select name="from" required>${tOpts}</select></label><label class="field">Vaduojantis mokytojas<select name="to" required>${tOpts}</select></label><label class="field">Nuo<input type="date" name="dFrom" required value="${TODAY()}"></label><label class="field">Iki<input type="date" name="dTo" required value="${addDays(TODAY(),6)}"></label><button class="btn pri">Sukurti</button></form></div>
    <div class="sheet scroll">${core.subs.length?`<table><thead><tr><th>Vaduojamas</th><th>Vaduojantis</th><th>Laikotarpis</th><th></th></tr></thead><tbody>${core.subs.map(s=>`<tr><td>${esc(uNameFL(s.from))}</td><td>${esc(uNameFL(s.to))}</td><td>${s.dFrom} – ${s.dTo}</td><td><button class="x" data-act="delSub" data-v="${s.id}" aria-label="Ištrinti">×</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">Pavadavimų nėra.</div>`}</div>`
   :`<div class="sheet pad" style="margin-bottom:14px"><form data-form="addHeadSub" class="bar" style="margin:0"><label class="field">Klasė<select name="classId" required>${core.classes.map(c=>`<option value="${c.id}">${esc(c.name)}${c.headTeacherId?` (${esc(uNameFL(c.headTeacherId))})`:""}</option>`).join("")}</select></label><label class="field">Vaduojantis mokytojas<select name="to" required>${tOpts}</select></label><label class="field">Nuo<input type="date" name="dFrom" required value="${TODAY()}"></label><label class="field">Iki<input type="date" name="dTo" required value="${addDays(TODAY(),6)}"></label><button class="btn pri">Sukurti</button></form></div>
    <div class="sheet scroll">${core.headSubs.length?`<table><thead><tr><th>Klasė</th><th>Vaduojantis</th><th>Laikotarpis</th><th></th></tr></thead><tbody>${core.headSubs.map(s=>`<tr><td>${esc(clsName(s.classId))}</td><td>${esc(uNameFL(s.to))}</td><td>${s.dFrom} – ${s.dTo}</td><td><button class="x" data-act="delHeadSub" data-v="${s.id}" aria-label="Ištrinti">×</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">Klasės vadovų pavadavimų nėra.</div>`}</div>`;
  return `<h1>Pavadavimai</h1><p class="lead">Vaduojantis mokytojas matys vaduojamo mokytojo tvarkaraštį ir nurodytomis dienomis galės pildyti pamokas: temą, įvertinimus, pagyrimus ir pastabas. Klasės vadovo pavaduotojas gauna klasės vadovo funkcijas.</p>
  <div class="tabs"><button aria-selected="${tab==="t"}" data-act="subTab" data-v="t">Mokytojų pavadavimai</button><button aria-selected="${tab==="h"}" data-act="subTab" data-v="h">Klasės vadovo pavadavimas</button></div>${body}`;};
VIEWS.a_tt=()=>{const tOpts=teachers().map(t=>[t.id,`${t.last} ${t.first}`]);ensureIn("ttTeacher",tOpts);if(!ui.ttTeacher)return `<h1>Mokytojų tvarkaraščiai</h1><div class="sheet empty">Mokytojų nėra.</div>`;
  return `<h1>Mokytojų tvarkaraščiai</h1><p class="lead">Mokytojų susidaryti pamokų tvarkaraščiai (tik peržiūra).</p><div class="bar">${sel("ttTeacher",tOpts,ui.ttTeacher,"Mokytojas")}${weekNav()}</div>${weekGrid(teacherGroups(ui.ttTeacher,false).map(g=>g.id),{ro:true})}`;};

/* ---- Ataskaitos ---- */
VIEWS.a_reports=()=>{const r=ui.rep;const tabs=[["keys","Naudotojų raktai"],["summary","Mokymosi apskaitos suvestinė"],["att","Lankomumo ataskaita"],["mr","Metiniai įvertinimai (MR)"]];
  let body="";const cOpts=[...core.classes].sort((a,b)=>lsort(a.name,b.name)).map(c=>[c.id,c.name]);
  if(r==="keys"){const who=ui.tab||"emp";const rows=who==="emp"?teachers().map(t=>[`${t.last} ${t.first}`,"Mokytojas",t.login?"(užsiregistravo)":t.key]):
      students().sort((a,b)=>lsort(clsName(a.classId)+a.last,clsName(b.classId)+b.last)).flatMap(s=>who==="stu"?[[`${s.last} ${s.first}`,clsName(s.classId),s.login?"(užsiregistravo)":s.key]]:(s.parentKeys||[]).map(p=>[`${s.last} ${s.first}`,clsName(s.classId),p.usedBy?`(panaudojo ${uNameFL(p.usedBy)})`:p.key]));
    body=`<div class="bar"><div class="tabs" style="margin:0;border:0">${[["emp","Darbuotojų raktai"],["stu","Mokinių raktai"],["par","Tėvų raktai"]].map(([k,n])=>`<button aria-selected="${who===k}" data-act="tab" data-v="${k}">${n}</button>`).join("")}</div><button class="btn" data-act="print">Spausdinti</button><button class="btn" data-act="exportKeys">Eksportuoti CSV</button></div>
      <div class="sheet scroll"><table><thead><tr><th>Asmuo</th><th>${who==="emp"?"Pareigos":"Klasė"}</th><th>Raktas</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x[0])}</td><td>${esc(x[1])}</td><td class="mono">${esc(x[2])}</td></tr>`).join("")}</tbody></table></div>
      <p class="small muted">Registracija atliekama prisijungimo lange, skirtuke „Registracija“.</p>`;}
  else if(r==="summary"||r==="att"||r==="mr"){ensureIn("repCls",cOpts);if(!ui.repCls)return `<h1>Ataskaitos</h1><div class="sheet empty">Klasių nėra.</div>`;const sys=sysOfClass(ui.repCls);const pOpts=periodOpts(sys,true);ensureIn("repPid",pOpts,"Y");
    const t=r==="mr"?reportMR():r==="summary"?reportSummary(ui.repCls,ui.repPid):reportAtt(ui.repCls,ui.repPid);
    body=`<div class="bar">${r==="mr"?"":sel("repCls",cOpts,ui.repCls,"Klasė")+sel("repPid",pOpts,ui.repPid,"Laikotarpis")}<button class="btn" data-act="exportRep">Eksportuoti CSV</button>${r==="mr"?'<button class="btn" data-act="exportXml">Rodyti XML</button>':""}<button class="btn" data-act="print">Spausdinti</button></div>${t.html}`;}
  return `<h1>Ataskaitos</h1><div class="tabs">${tabs.map(([k,n])=>`<button aria-selected="${r===k}" data-act="rep" data-v="${k}">${n}</button>`).join("")}</div>${body}`;};
function reportSummary(cid,pid){const ss=classStudents(cid);const gs=core.groups.filter(g=>g.students.some(s=>ss.find(x=>x.id===s)));const subs=[...new Set(gs.map(g=>g.subjectId))].sort((a,b)=>lsort(subjName(a),subjName(b)));
  const rows=ss.map(s=>{const vals=subs.map(sb=>{const g=gs.find(x=>x.subjectId===sb&&x.students.includes(s.id));if(!g)return null;const pg=G(g.id).pg[s.id]||{};return pg[pid]??null;});const n=vals.filter(v=>typeof v==="number");return{s,vals,avg:n.length?n.reduce((a,b)=>a+b,0)/n.length:null};});
  const head=["Mokinys",...subs.map(subjName),"Vidurkis"];
  return{csv:[head,...rows.map(r=>[`${r.s.last} ${r.s.first}`,...r.vals.map(v=>v==null?"":VLABEL[v]??v),r.avg==null?"":r.avg.toFixed(2)])],
    html:`<div class="sheet scroll"><table><thead><tr>${head.map((h,i)=>`<th class="${i?"num":""}">${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.s.last)} ${esc(r.s.first)}</td>${r.vals.map(v=>`<td class="num">${vchip(v)}</td>`).join("")}<td class="num"><b>${fmtAvg(r.avg)}</b></td></tr>`).join("")}</tbody></table></div><p class="small muted">${PNAME[pid]||""} laikotarpio (išvestiniai) įvertinimai. Tušti langeliai — laikotarpio pažymys dar neišvestas.</p>`};}
function reportAtt(cid,pid){const ss=classStudents(cid);const rows=ss.map(s=>{const a=[];studentGroups(s.id).forEach(g=>G(g.id).att.forEach(x=>{if(x.s===s.id&&inPeriod(x.d,pid))a.push(x);}));const n=a.filter(x=>x.m==="n");const j=n.filter(x=>x.j);const byCode=JUST.map(([k])=>j.filter(x=>x.j===k).length);return[`${s.last} ${s.first}`,n.length,j.length,n.length-j.length,a.filter(x=>x.m==="pv").length,...byCode];});
  const head=["Mokinys","Praleista","Pateisinta","Nepateisinta","Pavėlavimai",...JUST.map(([k])=>k)];
  return{csv:[head,...rows],html:`<div class="sheet scroll"><table><thead><tr>${head.map((h,i)=>`<th class="${i?"num":""}" ${i>4?`title="${esc(JUST_NAME[h])}"`:""}>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td class="${i?"num":""}" ${i===3&&c?'style="color:var(--pen);font-weight:700"':""}>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`};}
function reportMR(){const rows=[];students().sort((a,b)=>lsort(clsName(a.classId)+a.last,clsName(b.classId)+b.last)).forEach(s=>studentGroups(s.id).forEach(g=>{const v=(G(g.id).pg[s.id]||{}).Y;rows.push([`${s.last} ${s.first}`,clsName(s.classId),subjName(g.subjectId),(subj(g.subjectId)||{}).code||"",v==null?"":VLABEL[v]??v]);}));
  const head=["Mokinys","Klasė","Dalykas","Kodas","Metinis"];
  return{csv:[head,...rows],html:`<p class="small muted">Metų pabaigoje metiniai įvertinimai perduodami į Mokinių registrą. Čia sugeneruojamas to paties turinio CSV ir XML failas.</p><div class="sheet scroll"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td>${i===4?(c===""?'<span class="muted">—</span>':`<b>${esc(c)}</b>`):esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`};}
function mrXml(){const y=core.settings.yearStart;let x=`<?xml version="1.0" encoding="UTF-8"?>\n<MetiniaiVertinimai mokslometai="${y}-${y+1}" mokykla="${esc(core.settings.school)}">\n`;
  students().forEach(s=>{x+=`  <Mokinys vardas="${esc(s.first)}" pavarde="${esc(s.last)}" klase="${esc(clsName(s.classId))}">\n`;studentGroups(s.id).forEach(g=>{const v=(G(g.id).pg[s.id]||{}).Y;if(v!=null)x+=`    <Dalykas pavadinimas="${esc(subjName(g.subjectId))}" kodas="${esc((subj(g.subjectId)||{}).code||"")}">${esc(VLABEL[v]??v)}</Dalykas>\n`;});x+=`  </Mokinys>\n`;});return x+"</MetiniaiVertinimai>\n";}
VIEWS.a_users=()=>{const roles=[["*","Visi"],["admin","Administratoriai"],["teacher","Mokytojai"],["student","Mokiniai"],["parent","Tėvai"]];ensureIn("tab",roles,"*");
  const list=Object.values(users).filter(u=>ui.tab==="*"||u.role===ui.tab).sort((a,b)=>lsort(a.role+a.last,b.role+b.last));
  return `<h1>Naudotojai</h1><p class="lead">Visos paskyros. Administratorius gali nustatyti laikiną slaptažodį (prisijungęs naudotojas turės jį pasikeisti), išjungti 2FA arba panaikinti registraciją, kad asmuo galėtų registruotis iš naujo su tuo pačiu raktu. Šie veiksmai atliekami per Supabase Edge funkciją „admin-users“.</p>
  <div class="bar">${sel("tab",roles,ui.tab,"Vaidmuo")}</div>
  <div class="sheet scroll"><table><thead><tr><th>Asmuo</th><th>Vaidmuo</th><th>Prisijungimas</th><th>El. paštas</th><th></th></tr></thead><tbody>${list.map(u=>`<tr><td>${esc(u.last)} ${esc(u.first)}${u.role==="parent"?`<div class="small muted">Vaikai: ${(u.childIds||[]).map(c=>esc(uNameFL(c))).join(", ")}</div>`:""}</td><td>${ROLE_NAME[u.role]}${u.role==="student"?" · "+esc(clsName(u.classId)):""}</td><td>${u.login?esc(u.login):'<span class="muted">neregistruotas</span>'}${u.mustChange?' <span class="tag i">laikinas slaptažodis</span>':""}</td><td>${esc(u.email||"")}</td>
   <td style="white-space:nowrap">${u.login&&u.id!==session?`<button class="btn sm" data-act="resetPw" data-v="${u.id}">Laikinas slaptažodis</button> <button class="btn sm" data-act="off2fa" data-v="${u.id}">Išjungti 2FA</button> ${u.role!=="parent"?`<button class="btn sm warn" data-act="unreg" data-v="${u.id}">Panaikinti registraciją</button>`:""}`:""}${u.role==="parent"?` <button class="btn sm warn" data-act="delParent" data-v="${u.id}">Šalinti</button>`:""}</td></tr>`).join("")}</tbody></table></div>
  <h2>Naujas administratorius</h2><div class="sheet pad"><form data-form="addAdmin" class="bar" style="margin:0"><label class="field">Vardas<input name="first" required></label><label class="field">Pavardė<input name="last" required></label><button class="btn">Sukurti (registruosis su darbuotojo raktu)</button></form></div>`;};
VIEWS.a_data=()=>`<h1>Duomenys</h1><p class="lead">Duomenys saugomi jūsų Supabase projekte. Prieigą prie kiekvieno įrašo riboja duomenų bazės taisyklės (Row Level Security): mokinys mato tik savo, tėvai — savo vaikų, mokytojas — savo grupių duomenis.</p>
  <div class="row"><button class="btn" data-act="exportAll">Atsarginė kopija (JSON)</button><button class="btn warn" data-act="wipe">Ištrinti visus duomenis</button></div>
  <p class="small muted">„Ištrinti visus duomenis“ pašalina klases, mokinius, mokytojus, grupes ir visus įrašus — lieka tik jūsų administratoriaus paskyra. Ištrintų asmenų prisijungimo paskyros lieka Supabase → Authentication sąraše — jas galima pašalinti ten.</p>`;
